-- Tabela padrão do Envers para guardar informações da revisão (timestamp, user, etc)
CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- Tabela de auditoria para Product (se Product for @Audited)
CREATE TABLE products_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    name VARCHAR(255),
    slug VARCHAR(255),
    description TEXT,
    price NUMERIC(19, 2),
    -- ADICIONE ESTA LINHA 👇
    discount_price NUMERIC(19, 2),
    image_url VARCHAR(255),
    -- Adicione outros campos de Product que você sabe que existem (rating, max_installments, etc)
    -- Se tiver relacionamento com category ou brand, lembre-se: category_id, brand_id
    category_id BIGINT,
    brand_id BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_products_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

-- Tabela de auditoria para ProductVariant (O erro atual)
CREATE TABLE product_variants_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    sku VARCHAR(255),
    stock_quantity INTEGER,
    price NUMERIC(19, 2),
    name VARCHAR(255),
    image_url VARCHAR(255),
    -- ADICIONE ESTA LINHA 👇
    product_id BIGINT, 
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_product_variants_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

-- Repita para outras entidades com @Audited (Users, Orders, etc)